青山さん写真変更
YFujitani/sugimotoya-corp-site pull request #15
Opened 2019-02-06 07:09 UTC by AFujitani

施工事例写真追加
ハウスクリーニングから価格表ページへのリンク追加→修正必要

2019-02-06 16:59 UTC, YFujitani commented
古いmasterからのブランチ切っているためコンフリクトしてます。
最新のmasterにリベースしてください。

2019-02-07 00:55 UTC, AFujitani commented
うん、コンフリクトしてるて気づいた。リベースします。

iPhoneから送信

2019/02/07 1:59、YFujitani <notifications@github.com>のメール:

> 古いmasterからのブランチ切っているためコンフリクトしてます。
> 最新のmasterにリベースしてください。
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-02-07 06:33 UTC, YFujitani commented
今回やったマージブランチはブランチの分岐元は古いままで、masterからfeature/aboutus2へマージしている形になっています。
コンフリクトは解消されるけど、コミット履歴をわかりやすくするため次回以降コンフリクトした場合はリベースでお願いです。

2019-02-07 06:37 UTC, YFujitani requested changes
ファイル名確認おねがいします。

2019-02-07 06:37 UTC, YFujitani commented on portfolio.html
>  						</div>
ファイル名`portfolio.html`から変えなかったっけ？

2019-02-07 07:33 UTC, AFujitani commented on portfolio.html
>  						</div>
> ファイル名確認おねがいします。
作業中に消すファイル間違えたから、とりあえず変えませんでした。
example.htmlに変更します。

> 今回やったマージブランチはブランチの分岐元は古いままで、masterからfeature/aboutus2へマージしている形になっています。
> コンフリクトは解消されるけど、コミット履歴をわかりやすくするため次回以降コンフリクトした場合はリベースでお願いです。

はい、了解です。

2019-02-09 05:06 UTC, merged