footerにinstagramのリンクを追加
YFujitani/sugimotoya-corp-site pull request #36
Opened 2019-02-18 08:21 UTC by AFujitani

コメント文外してリンク追加

2019-02-18 08:33 UTC, YFujitani requested changes
instagramのリンク追加対応の方はOKです。

google mapスマフォ対応用の修正を上書きしているっぽいので確認してください。

2019-02-18 08:33 UTC, YFujitani commented on access.html
> -						<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2803.4794516224156!2d139.2819029254754!3d35.680316783463944!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x601918d33164be
https://github.com/YFujitani/sugimotoya-corp-site/pull/29/files

この修正を元に戻す上書きしているっぽいです。
PR出してもらったブランチは最新のmasterから切られているようだけど。

2019-02-18 10:26 UTC, AFujitani commented on access.html
> -						<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2803.4794516224156!2d139.2819029254754!3d35.680316783463944!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x601918d33164be
はい、了解です。
自分のコミットちゃんと確認してからPRします。

2019-02-19 01:36 UTC, YFujitani commented
LGTM

2019-02-19 01:37 UTC, merged