Add: ハウスクリーニングの動画
YFujitani/sugimotoya-corp-site pull request #65
Opened 2020-08-18 06:38 UTC by AFujitani

トップページと施工事例のページの最初にリンクを貼りました。
埋め込もうかと思ったのですが、リンクを貼るというのが最初のご希望だったし、簡単で良いかなと思いました。
確認お願いします。

2020-08-18 06:53 UTC, YFujitani requested changes
<img width="657" alt="スクリーンショット 2020-08-18 15 51 45" src="https://user-images.githubusercontent.com/10205443/90480124-c40a1700-e16a-11ea-89d2-264e5cfbe51c.png">

ヘッダーのメニューと同様にオンマウス時もunder lineは不要で良いと思う。

2020-08-18 06:59 UTC, AFujitani commented
はい、了解です。

2020-08-18 07:01 UTC, AFujitani commented
オンマウス時というか、訪問済みだとlineが表示されてしマウみたい。

2020-08-19 02:38 UTC, AFujitani commented
ハウスクリーニングへ　と　b-plus-bunner の訪問済みのunderline出ないように修正しました。

2020-08-19 02:53 UTC, YFujitani approved these changes

2020-08-19 02:55 UTC, merged