Add: 電話 fax 地図
YFujitani/sugimotoya-corp-site pull request #72
Opened 2020-08-27 04:18 UTC by AFujitani

class="google-map"書き忘れたので、見てもらったら修正します。

2020-08-27 05:40 UTC, YFujitani commented
<img width="858" alt="スクリーンショット 2020-08-27 14 32 34" src="https://user-images.githubusercontent.com/10205443/91388477-61073700-e872-11ea-921a-1c9c8c89075f.png">

〒192-0041　東京都八王子市中野上町5-2-4進華ビル1Ｆ
TEL 042-649-7565
FAX 042-649-7566
sugimotoya.rehome@gmail.com

それぞれの行間が空きすぎ
pタグの `margin-bottom`  `1.5em` -> `0.5em`

sugimotoya.rehome@gmail.com と google map の間隔が狭い気が

あと、メールアドレスはのせるの？
- 問い合わせがあるのでアドレスは不要な気もする
- アドレスを乗せるとサイトをクロールする業者等から主にスパムメールが増えて面倒

なのであまり載せないほうが良いと思われる。
SUGIMOTOYAは企業なのでまた別の観点もあると思うけど。
ももさんに確認してください

2020-08-31 05:36 UTC, YFujitani requested changes

2020-08-31 05:36 UTC, YFujitani commented on access.html
> +						<p class="access">TEL<br /> 042-649-7565</p>
改行はいらなくないですか？？

2020-08-31 05:44 UTC, AFujitani commented on access.html
> +						<p class="access">TEL<br /> 042-649-7565</p>
iPhone実機で確認したら番号がまた表示されない。

2020-08-31 05:46 UTC, AFujitani commented on access.html
> +						<p class="access">TEL<br /> 042-649-7565</p>
タッチすると電話かけられるようになってるけど、表示されていない。。

2020-08-31 08:38 UTC, AFujitani commented
できました。

2020-08-31 08:45 UTC, YFujitani commented
<img width="177" alt="スクリーンショット 2020-08-31 17 44 04" src="https://user-images.githubusercontent.com/10205443/91700990-9fbe2980-ebb1-11ea-8edf-40d6d2a41e93.png">

<img width="497" alt="スクリーンショット 2020-08-31 17 45 29" src="https://user-images.githubusercontent.com/10205443/91701108-ca0fe700-ebb1-11ea-8378-4ca8578cca66.png">

左右がずれているのが気になります。

2020-08-31 20:02 UTC, AFujitani commented
修正できたと思います。

2020-09-01 01:04 UTC, YFujitani approved these changes

2020-09-01 01:05 UTC, merged